[package]
name = "electrs_index"
version = "0.1.0"
authors = ["Roman Zeyde <me@romanzey.de>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
bitcoin = { version = "0.25", features = ["use-serde"] }
bitcoincore-rpc = "0.12"
chrono = "0.4"
clap = "2.33"
env_logger = "0.7"
hyper = "0.10"
log = "0.4"
prometheus = { version = "0.10", features = ["process"] }
rocksdb = "^0.15.0"
rust-crypto = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
